sonar.projectKey=cloudops-java-taskhub
sonar.projectName=CloudOps Java TaskHub
sonar.projectVersion=1.0.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.sourceEncoding=UTF-8
