name: Master Ci-java-cloudops workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    gitleak-scan:
      uses: ./.github/workflows/gitleak-scan.yml
    
    linting:
      needs: gitleak-scan
      uses: ./.github/workflows/lint.yml

    codeql-analysis:
      needs: linting
      uses: ./.github/workflows/code-quality.yml

    snyk-scan:
      needs: codeql-analysis
      uses: ./.github/workflows/sca.yml